# Generated by Django 4.2.3 on 2023-07-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_floor', models.IntegerField(default=0)),
                ('max_floor', models.IntegerField()),
                ('is_operational', models.BooleanField(default=True)),
            ],
        ),
    ]
