# Generated by Django 4.2.3 on 2023-07-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterElevator', '0003_rename_elevator_id_elevatorrequest_elevator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevatorrequest',
            name='elevator',
            field=models.IntegerField(),
        ),
    ]
